import { describe, expect, it } from "vitest";
import {
  generateAutolinkingCMake,
  generateAutolinkingRegistration,
  readModuleCodegenConfig,
} from "./autolinking-cmake.ts";
import type { AutolinkedLibrary } from "./linux-autolinking-types.ts";

const binaryDirectory = `$${"{"}CMAKE_BINARY_DIR}`;

const cppLibrary: AutolinkedLibrary = {
  cmakeListsPath: "/node_modules/react-native-cpp-library/android/CMakeLists.txt",
  codegenName: "CppLibrarySpec",
  kind: "linked",
  message: "react-native-cpp-library: linked by the cxx-fallback rule",
  moduleHeaderName: "CppLibraryImpl",
  moduleName: "react-native-cpp-library",
  packageName: "react-native-cpp-library",
  rule: "cxx-fallback",
};

const explicitLibrary: AutolinkedLibrary = {
  cmakeListsPath: "/node_modules/@scope/explicit/linux/CMakeLists.txt",
  codegenName: null,
  kind: "linked",
  message: "@scope/explicit: linked by the explicit rule",
  moduleHeaderName: null,
  moduleName: null,
  packageName: "@scope/explicit",
  rule: "explicit",
};

describe("generateAutolinkingCMake", () => {
  it("defines each codegen target, adds each library's own CMakeLists unchanged and lists its target", () => {
    expect(generateAutolinkingCMake([explicitLibrary, cppLibrary], "/app/build/autolinking/codegen")).toBe(
      [
        "# Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.",
        "set(CMAKE_POLICY_VERSION_MINIMUM 3.5)",
        "set(RNL_AUTOLINKED_TARGETS)",
        `set(RNL_AUTOLINKING_SOURCES "$${"{"}CMAKE_CURRENT_LIST_DIR}/rnl_autolinking.cpp")`,
        "",
        "# @scope/explicit: explicit",
        `add_subdirectory("/node_modules/@scope/explicit/linux" "${binaryDirectory}/autolinking/@scope/explicit")`,
        "",
        "# react-native-cpp-library: cxx-fallback",
        "add_library(react_codegen_CppLibrarySpec INTERFACE)",
        'target_include_directories(react_codegen_CppLibrarySpec INTERFACE "/app/build/autolinking/codegen/CppLibrarySpec")',
        "target_link_libraries(react_codegen_CppLibrarySpec INTERFACE jsi react_nativemodule_core)",
        `add_subdirectory("/node_modules/react-native-cpp-library/android" "${binaryDirectory}/autolinking/react-native-cpp-library")`,
        "list(APPEND RNL_AUTOLINKED_TARGETS react-native-cpp-library)",
        "",
      ].join("\n"),
    );
  });
});

describe("generateAutolinkingRegistration", () => {
  it("registers each named C++ TurboModule into the global module map", () => {
    expect(generateAutolinkingRegistration([explicitLibrary, cppLibrary])).toBe(
      [
        "// Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.",
        "#include <ReactCommon/CxxTurboModuleUtils.h>",
        "",
        "#include <CppLibraryImpl.h>",
        "",
        "#include <memory>",
        "#include <string>",
        "#include <utility>",
        "",
        "namespace facebook::react {",
        "namespace {",
        "",
        "const bool autolinkedModulesRegistered = [] {",
        "    registerCxxModuleToGlobalModuleMap(std::string(CppLibraryImpl::kModuleName),",
        "                                       [](std::shared_ptr<CallInvoker> jsInvoker) {",
        "                                           return std::make_shared<CppLibraryImpl>(std::move(jsInvoker));",
        "                                       });",
        "    return true;",
        "}();",
        "",
        "} // namespace",
        "} // namespace facebook::react",
        "",
      ].join("\n"),
    );
  });
});

describe("readModuleCodegenConfig", () => {
  it("reads the name and spec directory of a modules or all library", () => {
    const packageJson = JSON.stringify({
      codegenConfig: { jsSrcsDir: "src", name: "CppLibrarySpec", type: "modules" },
    });

    expect(readModuleCodegenConfig(packageJson)).toStrictEqual({ jsSourceDirectory: "src", name: "CppLibrarySpec" });
  });

  it.each([
    ["a package with no codegenConfig", {}],
    ["a package.json that is not an object", []],
    ["a components-only library", { codegenConfig: { jsSrcsDir: "src", name: "ViewSpec", type: "components" } }],
    ["a config without a name", { codegenConfig: { jsSrcsDir: "src", type: "all" } }],
    ["a config without a spec directory", { codegenConfig: { name: "Spec", type: "all" } }],
  ])("answers null for %s", (_description, packageJson) => {
    expect(readModuleCodegenConfig(JSON.stringify(packageJson))).toBeNull();
  });
});
