import type { AutolinkedLibrary, CodegenLibrary } from "./linux-autolinking-types.ts";
import path from "node:path";

const generatedNotice = "Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.";
const NO_COMPONENTS = 0;
const codegenTypes: ReadonlySet<unknown> = new Set(["all", "components", "modules"]);

const cmakeVariable = (name: string): string => `$${"{"}${name}}`;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * A library's `codegenConfig`: its `name`, which is also the suffix of the `react_codegen_<name>` target the
 * library's own CMakeLists links, and the `jsSrcsDir` its module and component specs live in. `null` for a
 * library with no codegen. Keys under `codegenConfig.linux` override the shared ones (#21), as react-native-windows
 * reads `codegenConfig.windows`.
 */
const readCodegenConfig = (
  packageJsonContents: string,
): { readonly jsSourceDirectory: string; readonly name: string } | null => {
  const packageJson: unknown = JSON.parse(packageJsonContents);
  const sharedConfig = isRecord(packageJson) ? packageJson["codegenConfig"] : null;
  const codegenConfig =
    isRecord(sharedConfig) && isRecord(sharedConfig["linux"])
      ? { ...sharedConfig, ...sharedConfig["linux"] }
      : sharedConfig;

  if (!isRecord(codegenConfig) || !codegenTypes.has(codegenConfig["type"])) {
    return null;
  }

  const { jsSrcsDir, name } = codegenConfig;

  return typeof name === "string" && typeof jsSrcsDir === "string" ? { jsSourceDirectory: jsSrcsDir, name } : null;
};

const moduleTargetLines = (name: string, includeDirectory: string): readonly string[] => [
  `add_library(react_codegen_${name} INTERFACE)`,
  `target_include_directories(react_codegen_${name} INTERFACE "${includeDirectory}")`,
  `target_link_libraries(react_codegen_${name} INTERFACE jsi react_nativemodule_core)`,
];

/** The generated props, shadow nodes, event emitters, states and descriptors compile against core's renderer. */
const componentTargetLines = (name: string, includeDirectory: string): readonly string[] => [
  `file(GLOB RNL_CODEGEN_${name}_SOURCES "${path.join(includeDirectory, "react", "renderer", "components", name)}/*.cpp")`,
  `add_library(react_codegen_${name} STATIC ${cmakeVariable(`RNL_CODEGEN_${name}_SOURCES`)})`,
  `target_include_directories(react_codegen_${name} PUBLIC "${includeDirectory}")`,
  `target_compile_options(react_codegen_${name} PRIVATE -fexceptions -frtti)`,
  `target_link_libraries(react_codegen_${name} PUBLIC jsi react_nativemodule_core react_renderer_componentregistry react_renderer_core react_renderer_graphics rrc_view)`,
  `list(APPEND RNL_AUTOLINKED_TARGETS react_codegen_${name})`,
];

const codegenTargetLines = ({ components, name }: CodegenLibrary, codegenDirectory: string): readonly string[] => [
  "",
  `# codegen: ${name}`,
  ...(components.length === NO_COMPONENTS ? moduleTargetLines : componentTargetLines)(
    name,
    path.join(codegenDirectory, name),
  ),
];

const libraryLines = (library: AutolinkedLibrary): readonly string[] => [
  "",
  `# ${library.packageName}: ${library.rule}`,
  `add_subdirectory("${path.dirname(library.cmakeListsPath)}" "${cmakeVariable("CMAKE_BINARY_DIR")}/autolinking/${library.packageName}")`,
  ...(library.moduleName === null ? [] : [`list(APPEND RNL_AUTOLINKED_TARGETS ${library.moduleName})`]),
];

/**
 * Issue #147: the one CMake file an app build includes through `RNL_AUTOLINKING_CMAKE`. It defines every
 * dependency's `react_codegen_<name>` target first, since a library's own CMakeLists links it by that name, then
 * adds each linked library's CMakeLists unchanged and lists its target for the host to link. A codegen target with
 * components compiles them and is linked by the host itself (#149). `CMAKE_POLICY_VERSION_MINIMUM` is set because
 * the `cpp-library` template declares `cmake_minimum_required(VERSION 3.4.1)`, which CMake 4 otherwise refuses.
 */
const generateAutolinkingCMake = (
  libraries: readonly AutolinkedLibrary[],
  codegenLibraries: readonly CodegenLibrary[],
  codegenDirectory: string,
): string =>
  [
    `# ${generatedNotice}`,
    "set(CMAKE_POLICY_VERSION_MINIMUM 3.5)",
    "set(RNL_AUTOLINKED_TARGETS)",
    `set(RNL_AUTOLINKING_SOURCES "${cmakeVariable("CMAKE_CURRENT_LIST_DIR")}/rnl_autolinking.cpp")`,
    ...codegenLibraries.flatMap((codegenLibrary) => codegenTargetLines(codegenLibrary, codegenDirectory)),
    ...libraries.flatMap((library) => libraryLines(library)),
    "",
  ].join("\n");

const registrationLines = (library: { moduleHeaderName: string; packageName: string }): readonly string[] => [
  `    registerAutolinkedModule(std::string(${library.moduleHeaderName}::kModuleName), "${library.packageName}",`,
  "                             [](std::shared_ptr<CallInvoker> jsInvoker) {",
  `                                 return std::make_shared<${library.moduleHeaderName}>(std::move(jsInvoker));`,
  "                             });",
];

/** Upstream's `registerCxxModuleToGlobalModuleMap` replaces a name silently; two libraries claiming one must not. */
const duplicateGuardLines: readonly string[] = [
  "void registerAutolinkedModule(",
  "    std::string name, const char* packageName,",
  "    std::function<std::shared_ptr<TurboModule>(std::shared_ptr<CallInvoker>)> moduleProvider) {",
  "    if (globalExportedCxxTurboModuleMap().contains(name)) {",
  '        std::cerr << "[autolinking] " << packageName << " registers the TurboModule \'" << name',
  '                  << "\', which another autolinked library already registered" << std::endl;',
  "        std::abort();",
  "    }",
  "",
  "    registerCxxModuleToGlobalModuleMap(std::move(name), std::move(moduleProvider));",
  "}",
  "",
];

/**
 * The C++ half: every C++ TurboModule a library names by `cxxModuleHeaderName` is registered into upstream's
 * `globalExportedCxxTurboModuleMap`, exactly as the `cpp-library` template's iOS `OnLoad.mm` does and with the
 * class-name convention Android's generated autolinking uses. The file is compiled into the host executable
 * itself, so the static initializer is never dropped by the linker the way one inside a static archive can be, and
 * it runs before `main` and so before `TurboModuleRegistry` copies the map. A name two libraries both register
 * aborts at startup naming the second package, rather than one module silently replacing the other (#148). Each
 * codegen-generated component descriptor joins core's autolinked provider list the same way, before `FabricHost`
 * reads it (#149).
 */
const generateAutolinkingRegistration = (
  libraries: readonly AutolinkedLibrary[],
  codegenLibraries: readonly CodegenLibrary[],
): string => {
  const modules = libraries.flatMap(({ moduleHeaderName, packageName }) =>
    moduleHeaderName === null ? [] : [{ moduleHeaderName, packageName }],
  );
  const componentLibraries = codegenLibraries.filter(({ components }) => components.length > NO_COMPONENTS);

  return [
    `// ${generatedNotice}`,
    "#include <AutolinkedComponents.h>",
    "#include <ReactCommon/CxxTurboModuleUtils.h>",
    "",
    ...modules.map(({ moduleHeaderName }) => `#include <${moduleHeaderName}.h>`),
    ...componentLibraries.map(({ name }) => `#include <react/renderer/components/${name}/ComponentDescriptors.h>`),
    "",
    "#include <cstdlib>",
    "#include <functional>",
    "#include <iostream>",
    "#include <memory>",
    "#include <string>",
    "#include <utility>",
    "",
    "namespace facebook::react {",
    "namespace {",
    "",
    ...duplicateGuardLines,
    "const bool autolinkedModulesRegistered = [] {",
    ...modules.flatMap((module) => registrationLines(module)),
    ...componentLibraries.flatMap(({ components }) =>
      components.map(
        (component) =>
          `    react_native_linux::autolinkedComponentDescriptorProviders().push_back(concreteComponentDescriptorProvider<${component}ComponentDescriptor>());`,
      ),
    ),
    "    return true;",
    "}();",
    "",
    "} // namespace",
    "} // namespace facebook::react",
    "",
  ].join("\n");
};

export { generateAutolinkingCMake, generateAutolinkingRegistration, readCodegenConfig };
