import type { AutolinkedLibrary } from "./linux-autolinking-types.ts";
import path from "node:path";

const generatedNotice = "Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.";
const moduleCodegenTypes: ReadonlySet<unknown> = new Set(["all", "modules"]);

const cmakeVariable = (name: string): string => `$${"{"}${name}}`;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * The `codegenConfig` of a library whose spec set includes TurboModules: its `name`, which is also the suffix of
 * the `react_codegen_<name>` target the library's own CMakeLists links, and the `jsSrcsDir` its specs live in.
 * `null` for a library with no module specs.
 */
const readModuleCodegenConfig = (
  packageJsonContents: string,
): { readonly jsSourceDirectory: string; readonly name: string } | null => {
  const packageJson: unknown = JSON.parse(packageJsonContents);
  const codegenConfig = isRecord(packageJson) ? packageJson["codegenConfig"] : null;

  if (!isRecord(codegenConfig) || !moduleCodegenTypes.has(codegenConfig["type"])) {
    return null;
  }

  const { jsSrcsDir, name } = codegenConfig;

  return typeof name === "string" && typeof jsSrcsDir === "string" ? { jsSourceDirectory: jsSrcsDir, name } : null;
};

const codegenTargetLines = (codegenName: string, codegenDirectory: string): readonly string[] => [
  `add_library(react_codegen_${codegenName} INTERFACE)`,
  `target_include_directories(react_codegen_${codegenName} INTERFACE "${path.join(codegenDirectory, codegenName)}")`,
  `target_link_libraries(react_codegen_${codegenName} INTERFACE jsi react_nativemodule_core)`,
];

const libraryLines = (library: AutolinkedLibrary, codegenDirectory: string): readonly string[] => [
  "",
  `# ${library.packageName}: ${library.rule}`,
  ...(library.codegenName === null ? [] : codegenTargetLines(library.codegenName, codegenDirectory)),
  `add_subdirectory("${path.dirname(library.cmakeListsPath)}" "${cmakeVariable("CMAKE_BINARY_DIR")}/autolinking/${library.packageName}")`,
  ...(library.moduleName === null ? [] : [`list(APPEND RNL_AUTOLINKED_TARGETS ${library.moduleName})`]),
];

/**
 * Issue #147: the one CMake file an app build includes through `RNL_AUTOLINKING_CMAKE`. Per library it defines the
 * `react_codegen_<name>` target the library's own CMakeLists already links, adds that CMakeLists unchanged, and
 * lists its target for the host to link. `CMAKE_POLICY_VERSION_MINIMUM` is set because the `cpp-library` template
 * declares `cmake_minimum_required(VERSION 3.4.1)`, which CMake 4 otherwise refuses.
 */
const generateAutolinkingCMake = (libraries: readonly AutolinkedLibrary[], codegenDirectory: string): string =>
  [
    `# ${generatedNotice}`,
    "set(CMAKE_POLICY_VERSION_MINIMUM 3.5)",
    "set(RNL_AUTOLINKED_TARGETS)",
    `set(RNL_AUTOLINKING_SOURCES "${cmakeVariable("CMAKE_CURRENT_LIST_DIR")}/rnl_autolinking.cpp")`,
    ...libraries.flatMap((library) => libraryLines(library, codegenDirectory)),
    "",
  ].join("\n");

const registrationLines = (moduleHeaderName: string): readonly string[] => [
  `    registerCxxModuleToGlobalModuleMap(std::string(${moduleHeaderName}::kModuleName),`,
  "                                       [](std::shared_ptr<CallInvoker> jsInvoker) {",
  `                                           return std::make_shared<${moduleHeaderName}>(std::move(jsInvoker));`,
  "                                       });",
];

/**
 * The C++ half: every C++ TurboModule a library names by `cxxModuleHeaderName` is registered into upstream's
 * `globalExportedCxxTurboModuleMap`, exactly as the `cpp-library` template's iOS `OnLoad.mm` does and with the
 * class-name convention Android's generated autolinking uses. The file is compiled into the host executable
 * itself, so the static initializer is never dropped by the linker the way one inside a static archive can be.
 */
const generateAutolinkingRegistration = (libraries: readonly AutolinkedLibrary[]): string => {
  const moduleHeaderNames = libraries.flatMap((library) =>
    library.moduleHeaderName === null ? [] : [library.moduleHeaderName],
  );

  return [
    `// ${generatedNotice}`,
    "#include <ReactCommon/CxxTurboModuleUtils.h>",
    "",
    ...moduleHeaderNames.map((moduleHeaderName) => `#include <${moduleHeaderName}.h>`),
    "",
    "#include <memory>",
    "#include <string>",
    "#include <utility>",
    "",
    "namespace facebook::react {",
    "namespace {",
    "",
    "const bool autolinkedModulesRegistered = [] {",
    ...moduleHeaderNames.flatMap((moduleHeaderName) => registrationLines(moduleHeaderName)),
    "    return true;",
    "}();",
    "",
    "} // namespace",
    "} // namespace facebook::react",
    "",
  ].join("\n");
};

export { generateAutolinkingCMake, generateAutolinkingRegistration, readModuleCodegenConfig };
