import type { AutolinkedLibrary } from "./linux-autolinking-types.ts";
import path from "node:path";

const generatedNotice = "Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.";
const moduleCodegenTypes: ReadonlySet<unknown> = new Set(["all", "modules"]);

const cmakeVariable = (name: string): string => `$${"{"}${name}}`;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * The `codegenConfig` of a library whose spec set includes TurboModules: its `name`, which is also the suffix of
 * the `react_codegen_<name>` target the library's own CMakeLists links, and the `jsSrcsDir` its specs live in.
 * `null` for a library with no module specs.
 */
const readModuleCodegenConfig = (
  packageJsonContents: string,
): { readonly jsSourceDirectory: string; readonly name: string } | null => {
  const packageJson: unknown = JSON.parse(packageJsonContents);
  const codegenConfig = isRecord(packageJson) ? packageJson["codegenConfig"] : null;

  if (!isRecord(codegenConfig) || !moduleCodegenTypes.has(codegenConfig["type"])) {
    return null;
  }

  const { jsSrcsDir, name } = codegenConfig;

  return typeof name === "string" && typeof jsSrcsDir === "string" ? { jsSourceDirectory: jsSrcsDir, name } : null;
};

const codegenTargetLines = (codegenName: string, codegenDirectory: string): readonly string[] => [
  `add_library(react_codegen_${codegenName} INTERFACE)`,
  `target_include_directories(react_codegen_${codegenName} INTERFACE "${path.join(codegenDirectory, codegenName)}")`,
  `target_link_libraries(react_codegen_${codegenName} INTERFACE jsi react_nativemodule_core)`,
];

const libraryLines = (library: AutolinkedLibrary, codegenDirectory: string): readonly string[] => [
  "",
  `# ${library.packageName}: ${library.rule}`,
  ...(library.codegenName === null ? [] : codegenTargetLines(library.codegenName, codegenDirectory)),
  `add_subdirectory("${path.dirname(library.cmakeListsPath)}" "${cmakeVariable("CMAKE_BINARY_DIR")}/autolinking/${library.packageName}")`,
  ...(library.moduleName === null ? [] : [`list(APPEND RNL_AUTOLINKED_TARGETS ${library.moduleName})`]),
];

/**
 * Issue #147: the one CMake file an app build includes through `RNL_AUTOLINKING_CMAKE`. Per library it defines the
 * `react_codegen_<name>` target the library's own CMakeLists already links, adds that CMakeLists unchanged, and
 * lists its target for the host to link. `CMAKE_POLICY_VERSION_MINIMUM` is set because the `cpp-library` template
 * declares `cmake_minimum_required(VERSION 3.4.1)`, which CMake 4 otherwise refuses.
 */
const generateAutolinkingCMake = (libraries: readonly AutolinkedLibrary[], codegenDirectory: string): string =>
  [
    `# ${generatedNotice}`,
    "set(CMAKE_POLICY_VERSION_MINIMUM 3.5)",
    "set(RNL_AUTOLINKED_TARGETS)",
    `set(RNL_AUTOLINKING_SOURCES "${cmakeVariable("CMAKE_CURRENT_LIST_DIR")}/rnl_autolinking.cpp")`,
    ...libraries.flatMap((library) => libraryLines(library, codegenDirectory)),
    "",
  ].join("\n");

const registrationLines = (library: { moduleHeaderName: string; packageName: string }): readonly string[] => [
  `    registerAutolinkedModule(std::string(${library.moduleHeaderName}::kModuleName), "${library.packageName}",`,
  "                             [](std::shared_ptr<CallInvoker> jsInvoker) {",
  `                                 return std::make_shared<${library.moduleHeaderName}>(std::move(jsInvoker));`,
  "                             });",
];

/** Upstream's `registerCxxModuleToGlobalModuleMap` replaces a name silently; two libraries claiming one must not. */
const duplicateGuardLines: readonly string[] = [
  "void registerAutolinkedModule(",
  "    std::string name, const char* packageName,",
  "    std::function<std::shared_ptr<TurboModule>(std::shared_ptr<CallInvoker>)> moduleProvider) {",
  "    if (globalExportedCxxTurboModuleMap().contains(name)) {",
  '        std::cerr << "[autolinking] " << packageName << " registers the TurboModule \'" << name',
  '                  << "\', which another autolinked library already registered" << std::endl;',
  "        std::abort();",
  "    }",
  "",
  "    registerCxxModuleToGlobalModuleMap(std::move(name), std::move(moduleProvider));",
  "}",
  "",
];

/**
 * The C++ half: every C++ TurboModule a library names by `cxxModuleHeaderName` is registered into upstream's
 * `globalExportedCxxTurboModuleMap`, exactly as the `cpp-library` template's iOS `OnLoad.mm` does and with the
 * class-name convention Android's generated autolinking uses. The file is compiled into the host executable
 * itself, so the static initializer is never dropped by the linker the way one inside a static archive can be, and
 * it runs before `main` and so before `TurboModuleRegistry` copies the map. A name two libraries both register
 * aborts at startup naming the second package, rather than one module silently replacing the other (#148).
 */
const generateAutolinkingRegistration = (libraries: readonly AutolinkedLibrary[]): string => {
  const modules = libraries.flatMap(({ moduleHeaderName, packageName }) =>
    moduleHeaderName === null ? [] : [{ moduleHeaderName, packageName }],
  );

  return [
    `// ${generatedNotice}`,
    "#include <ReactCommon/CxxTurboModuleUtils.h>",
    "",
    ...modules.map(({ moduleHeaderName }) => `#include <${moduleHeaderName}.h>`),
    "",
    "#include <cstdlib>",
    "#include <functional>",
    "#include <iostream>",
    "#include <memory>",
    "#include <string>",
    "#include <utility>",
    "",
    "namespace facebook::react {",
    "namespace {",
    "",
    ...duplicateGuardLines,
    "const bool autolinkedModulesRegistered = [] {",
    ...modules.flatMap((module) => registrationLines(module)),
    "    return true;",
    "}();",
    "",
    "} // namespace",
    "} // namespace facebook::react",
    "",
  ].join("\n");
};

export { generateAutolinkingCMake, generateAutolinkingRegistration, readModuleCodegenConfig };
