import type { AutolinkedLibrary, CodegenLibrary } from "./linux-autolinking-types.ts";
import {
  autolinkingCacheKey,
  generateAutolinkingCMake,
  generateAutolinkingRegistration,
  readCodegenConfig,
} from "./autolinking-cmake.ts";
import { describe, expect, it } from "vitest";

const binaryDirectory = `$${"{"}CMAKE_BINARY_DIR}`;
const moduleCodegen: CodegenLibrary = { components: [], name: "CppLibrarySpec" };
const componentCodegen: CodegenLibrary = { components: ["FixtureView"], name: "FixtureSpec" };

const cppLibrary: AutolinkedLibrary = {
  cmakeListsPath: "/node_modules/react-native-cpp-library/android/CMakeLists.txt",
  kind: "linked",
  message: "react-native-cpp-library: linked by the cxx-fallback rule",
  moduleHeaderName: "CppLibraryImpl",
  moduleName: "react-native-cpp-library",
  packageName: "react-native-cpp-library",
  rule: "cxx-fallback",
};

const explicitLibrary: AutolinkedLibrary = {
  cmakeListsPath: "/node_modules/@scope/explicit/linux/CMakeLists.txt",
  kind: "linked",
  message: "@scope/explicit: linked by the explicit rule",
  moduleHeaderName: null,
  moduleName: null,
  packageName: "@scope/explicit",
  rule: "explicit",
};

describe("generateAutolinkingCMake", () => {
  it("defines each codegen target, adds each library's own CMakeLists unchanged and lists its target", () => {
    expect(
      generateAutolinkingCMake(
        [explicitLibrary, cppLibrary],
        [moduleCodegen, componentCodegen],
        "/app/build/autolinking/codegen",
      ),
    ).toBe(
      [
        "# Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.",
        "set(CMAKE_POLICY_VERSION_MINIMUM 3.5)",
        "set(RNL_AUTOLINKED_TARGETS)",
        `set(RNL_AUTOLINKING_SOURCES "$${"{"}CMAKE_CURRENT_LIST_DIR}/rnl_autolinking.cpp")`,
        "",
        "# codegen: CppLibrarySpec",
        "add_library(react_codegen_CppLibrarySpec INTERFACE)",
        'target_include_directories(react_codegen_CppLibrarySpec INTERFACE "/app/build/autolinking/codegen/CppLibrarySpec")',
        "target_link_libraries(react_codegen_CppLibrarySpec INTERFACE jsi react_nativemodule_core)",
        "",
        "# codegen: FixtureSpec",
        'file(GLOB RNL_CODEGEN_FixtureSpec_SOURCES "/app/build/autolinking/codegen/FixtureSpec/react/renderer/components/FixtureSpec/*.cpp")',
        `add_library(react_codegen_FixtureSpec STATIC $${"{"}RNL_CODEGEN_FixtureSpec_SOURCES})`,
        'target_include_directories(react_codegen_FixtureSpec PUBLIC "/app/build/autolinking/codegen/FixtureSpec")',
        "target_compile_options(react_codegen_FixtureSpec PRIVATE -fexceptions -frtti)",
        "target_link_libraries(react_codegen_FixtureSpec PUBLIC jsi react_nativemodule_core react_renderer_componentregistry react_renderer_core react_renderer_graphics rrc_view)",
        "list(APPEND RNL_AUTOLINKED_TARGETS react_codegen_FixtureSpec)",
        "",
        "# @scope/explicit: explicit",
        `add_subdirectory("/node_modules/@scope/explicit/linux" "${binaryDirectory}/autolinking/@scope/explicit")`,
        "",
        "# react-native-cpp-library: cxx-fallback",
        `add_subdirectory("/node_modules/react-native-cpp-library/android" "${binaryDirectory}/autolinking/react-native-cpp-library")`,
        "list(APPEND RNL_AUTOLINKED_TARGETS react-native-cpp-library)",
        "",
      ].join("\n"),
    );
  });
});

describe("generateAutolinkingRegistration", () => {
  it("registers each C++ TurboModule, refusing a name registered twice, and each codegen component descriptor", () => {
    expect(generateAutolinkingRegistration([explicitLibrary, cppLibrary], [moduleCodegen, componentCodegen])).toBe(
      [
        "// Generated by scripts/autolink.ts from the autolinking verdicts (#146, #147). Do not edit.",
        "#include <AutolinkedComponents.h>",
        "#include <ReactCommon/CxxTurboModuleUtils.h>",
        "",
        "#include <CppLibraryImpl.h>",
        "#include <react/renderer/components/FixtureSpec/ComponentDescriptors.h>",
        "",
        "#include <cstdlib>",
        "#include <functional>",
        "#include <iostream>",
        "#include <memory>",
        "#include <string>",
        "#include <utility>",
        "",
        "namespace facebook::react {",
        "namespace {",
        "",
        "void registerAutolinkedModule(",
        "    std::string name, const char* packageName,",
        "    std::function<std::shared_ptr<TurboModule>(std::shared_ptr<CallInvoker>)> moduleProvider) {",
        "    if (globalExportedCxxTurboModuleMap().contains(name)) {",
        '        std::cerr << "[autolinking] " << packageName << " registers the TurboModule \'" << name',
        '                  << "\', which another autolinked library already registered" << std::endl;',
        "        std::abort();",
        "    }",
        "",
        "    registerCxxModuleToGlobalModuleMap(std::move(name), std::move(moduleProvider));",
        "}",
        "",
        "const bool autolinkedModulesRegistered = [] {",
        '    registerAutolinkedModule(std::string(CppLibraryImpl::kModuleName), "react-native-cpp-library",',
        "                             [](std::shared_ptr<CallInvoker> jsInvoker) {",
        "                                 return std::make_shared<CppLibraryImpl>(std::move(jsInvoker));",
        "                             });",
        "    react_native_linux::autolinkedComponentDescriptorProviders().push_back(concreteComponentDescriptorProvider<FixtureViewComponentDescriptor>());",
        "    return true;",
        "}();",
        "",
        "} // namespace",
        "} // namespace facebook::react",
        "",
      ].join("\n"),
    );
  });
});

describe("readCodegenConfig", () => {
  it.each(["modules", "components", "all"])("reads the name and spec directory of a %s library", (type) => {
    const packageJson = JSON.stringify({ codegenConfig: { jsSrcsDir: "src", name: "CppLibrarySpec", type } });

    expect(readCodegenConfig(packageJson)).toStrictEqual({ jsSourceDirectory: "src", name: "CppLibrarySpec" });
  });

  it("lets codegenConfig.linux override the shared keys", () => {
    const packageJson = JSON.stringify({
      codegenConfig: {
        jsSrcsDir: "src",
        linux: { jsSrcsDir: "src/linux", name: "LinuxSpec" },
        name: "Spec",
        type: "all",
      },
    });

    expect(readCodegenConfig(packageJson)).toStrictEqual({ jsSourceDirectory: "src/linux", name: "LinuxSpec" });
  });

  it.each([
    ["a package with no codegenConfig", {}],
    [
      "a linux override with an unknown type",
      { codegenConfig: { jsSrcsDir: "src", linux: { type: "views" }, name: "Spec", type: "all" } },
    ],
    ["a package.json that is not an object", []],
    ["an unknown codegen type", { codegenConfig: { jsSrcsDir: "src", name: "ViewSpec", type: "views" } }],
    ["a config without a name", { codegenConfig: { jsSrcsDir: "src", type: "all" } }],
    ["a config without a spec directory", { codegenConfig: { name: "Spec", type: "all" } }],
  ])("answers null for %s", (_description, packageJson) => {
    expect(readCodegenConfig(JSON.stringify(packageJson))).toBeNull();
  });
});

const files: Readonly<Record<string, string>> = {
  "/app/react-native.config.js": "export default {};",
  "/library/package.json": '{"version":"1.0.0"}',
};

const readFixture = (filePath: string): string | null => files[filePath] ?? null;
const readEmpty = (): string => "";

describe("autolinkingCacheKey", () => {
  it("is the same for the same inputs", () => {
    const inputs = ["/library/package.json", "/app/react-native.config.js"];

    expect(autolinkingCacheKey(inputs, readFixture)).toBe(autolinkingCacheKey(inputs, readFixture));
  });

  it("changes when an input's content changes", () => {
    const edited = (filePath: string): string | null =>
      filePath === "/library/package.json" ? '{"version":"1.0.1"}' : readFixture(filePath);

    expect(autolinkingCacheKey(["/library/package.json"], edited)).not.toBe(
      autolinkingCacheKey(["/library/package.json"], readFixture),
    );
  });

  it("tells an absent input from an empty one", () => {
    expect(autolinkingCacheKey(["/absent.json"], readFixture)).not.toBe(
      autolinkingCacheKey(["/absent.json"], readEmpty),
    );
  });

  it("changes when an input moves", () => {
    expect(autolinkingCacheKey(["/a/package.json"], readEmpty)).not.toBe(
      autolinkingCacheKey(["/b/package.json"], readEmpty),
    );
  });
});
