import {
  countDiffLines,
  findManifestProblems,
  minorsBehind,
  readOverrideEntries,
  renderOverrideReport,
} from "./override-report.ts";
import { describe, expect, it } from "vitest";

const derived = { file: "src-linux/Platform.linux.ts", issue: 29, type: "derived" };
const platform = { file: "index.ts", issue: 22, type: "platform" };
const overBudgetCount = 14;
const sameMinor = 0;
const twoMinors = 2;
const addedLineCount = 51;
const removedLineCount = 70;

describe("readOverrideEntries", () => {
  it("reads each override's file, type and issue, and an absent issue as null", () => {
    expect(
      readOverrideEntries({
        overrides: [
          { baseFile: "Platform.android.js", file: derived.file, issue: 29, type: "derived" },
          { file: "index.ts", type: "platform" },
        ],
      }),
    ).toStrictEqual([derived, { file: "index.ts", issue: null, type: "platform" }]);
  });

  it.each([[null], [{}], [{ overrides: {} }]])("refuses a manifest with no overrides array: %j", (manifest) => {
    expect(() => readOverrideEntries(manifest)).toThrow("the override manifest must have an overrides array");
  });

  it.each([[[null]], [[{ type: "derived" }]], [[{ file: "index.ts" }]]])(
    "refuses an override without a file and a type: %j",
    (overrides) => {
      expect(() => readOverrideEntries({ overrides })).toThrow("every override must name its file and its type");
    },
  );
});

describe("findManifestProblems", () => {
  it("accepts explained overrides within the budget", () => {
    expect(findManifestProblems([derived, platform])).toStrictEqual([]);
  });

  it("names every override that states no issue, and a count past the budget", () => {
    const unexplained = { ...platform, issue: null };
    const entries = Array.from({ length: overBudgetCount }, () => derived);

    expect(findManifestProblems([unexplained])).toStrictEqual(["index.ts states no issue as its reason"]);
    expect(findManifestProblems(entries)).toStrictEqual(["14 overrides exceed the budget of 13"]);
  });
});

describe("minorsBehind", () => {
  it("counts minors between the derived version and the vendored tag", () => {
    expect(minorsBehind("0.87.1", "v0.87.1")).toBe(sameMinor);
    expect(minorsBehind("0.86.4", "v0.88.0-rc.3")).toBe(twoMinors);
  });
});

describe("countDiffLines", () => {
  it("counts source lines resembling file headers across hunks", () => {
    expect(countDiffLines("--- a\n+++ b\n@@ -1 +1 @@\n---source\n+++source\n@@ -4 +4 @@\n-old\n+new")).toStrictEqual({
      addedLines: 2,
      removedLines: 2,
    });
  });

  it.each(["", "--- a\n+++ b"])("counts no changes without a hunk: %j", (diff) => {
    expect(countDiffLines(diff)).toStrictEqual({ addedLines: 0, removedLines: 0 });
  });

  it("counts added and removed lines without the file headers", () => {
    expect(countDiffLines("--- a\n+++ b\n@@ -1 +1,2 @@\n-old\n+new\n+more\n context")).toStrictEqual({
      addedLines: 2,
      removedLines: 1,
    });
  });
});

describe("renderOverrideReport", () => {
  it("lists every override with its size against upstream, its reason and the budget", () => {
    const rows = [
      { ...platform, ...countDiffLines("") },
      {
        ...derived,
        ...countDiffLines(
          `@@ -1,70 +1,51 @@\n${"+added\n".repeat(addedLineCount)}${"-removed\n".repeat(removedLineCount)}`,
        ),
      },
    ];

    expect(renderOverrideReport(rows, "0.86.4", "v0.87.1")).toBe(
      [
        "# Platform overrides",
        "",
        "Generated by `pnpm override:report` from `packages/core/overrides.json`; `pnpm validate` fails when it drifts.",
        "",
        "2 of 13 budgeted overrides, derived from React Native 0.86.4, 1 minors behind the vendored v0.87.1.",
        "",
        "| File | Type | Against upstream | Reason |",
        "| --- | --- | --- | --- |",
        "| `index.ts` | platform | new file | #22 |",
        "| `src-linux/Platform.linux.ts` | derived | +51 −70 | #29 |",
        "",
      ].join("\n"),
    );
  });
});
