/**
 * #86: the platform-override manifest (`packages/core/overrides.json`, react-native-platform-override's format) as
 * a reviewed number. Every entry states the issue that justifies it, the count stays inside ADR-0001's override
 * budget, and the checked-in report shows each override's size against upstream and its age in React Native
 * minors, so "should this still be forked?" is a review question with data.
 */
interface OverrideEntry {
  readonly file: string;
  readonly issue: number | null;
  readonly type: string;
}

interface OverrideReportRow extends OverrideEntry {
  readonly addedLines: number;
  readonly removedLines: number;
}

/** ADR-0001's override budget. Raising it is a reviewed edit to this number, with the reason in the pull request. */
const OVERRIDE_BUDGET = 13;
const MINOR_INDEX = 1;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const readOverrideEntries = (manifest: unknown): readonly OverrideEntry[] => {
  const overrides = isRecord(manifest) ? manifest["overrides"] : null;

  if (!Array.isArray(overrides)) {
    throw new TypeError("the override manifest must have an overrides array");
  }

  return overrides.map((entry: unknown) => {
    if (!isRecord(entry) || typeof entry["file"] !== "string" || typeof entry["type"] !== "string") {
      throw new TypeError("every override must name its file and its type");
    }

    return {
      file: entry["file"],
      issue: typeof entry["issue"] === "number" ? entry["issue"] : null,
      type: entry["type"],
    };
  });
};

/** What makes the manifest unacceptable regardless of upstream: an unexplained entry, or a count past the budget. */
const findManifestProblems = (entries: readonly OverrideEntry[]): readonly string[] => [
  ...entries.filter(({ issue }) => issue === null).map(({ file }) => `${file} states no issue as its reason`),
  ...(entries.length > OVERRIDE_BUDGET
    ? [`${String(entries.length)} overrides exceed the budget of ${String(OVERRIDE_BUDGET)}`]
    : []),
];

const minorOf = (version: string): number => Number(version.replace(/^v/u, "").split(".")[MINOR_INDEX]);

/** How many React Native minors the vendored pin has moved past the version the overrides were derived from. */
const minorsBehind = (baseVersion: string, vendoredVersion: string): number =>
  minorOf(vendoredVersion) - minorOf(baseVersion);

/** Counts the `+` and `-` lines of a unified diff, leaving out its `+++` and `---` file headers. */
const countDiffLines = (diff: string): { readonly addedLines: number; readonly removedLines: number } => {
  const lines = diff.split("\n");

  return {
    addedLines: lines.filter((line) => line.startsWith("+") && !line.startsWith("+++")).length,
    removedLines: lines.filter((line) => line.startsWith("-") && !line.startsWith("---")).length,
  };
};

const describeSize = ({ addedLines, removedLines, type }: OverrideReportRow): string =>
  type === "derived" ? `+${String(addedLines)} −${String(removedLines)}` : "new file";

const renderOverrideReport = (
  rows: readonly OverrideReportRow[],
  baseVersion: string,
  vendoredVersion: string,
): string =>
  [
    "# Platform overrides",
    "",
    "Generated by `pnpm override:report` from `packages/core/overrides.json`; `pnpm validate` fails when it drifts.",
    "",
    `${String(rows.length)} of ${String(OVERRIDE_BUDGET)} budgeted overrides, derived from React Native ${baseVersion}, ` +
      `${String(minorsBehind(baseVersion, vendoredVersion))} minors behind the vendored ${vendoredVersion}.`,
    "",
    "| File | Type | Against upstream | Reason |",
    "| --- | --- | --- | --- |",
    ...rows.map((row) => `| \`${row.file}\` | ${row.type} | ${describeSize(row)} | #${String(row.issue)} |`),
    "",
  ].join("\n");

export { countDiffLines, findManifestProblems, minorsBehind, readOverrideEntries, renderOverrideReport };
export type { OverrideEntry, OverrideReportRow };
