import type { DoctorCheck } from "./doctor-check.ts";

const semanticVersionPattern = /(?<version>\d+\.\d+\.\d+)/u;

const doctorChecks: readonly DoctorCheck[] = [
  {
    name: "CMake",
    probe: {
      candidateNames: ["cmake"],
      kind: "binary",
      minimumVersion: "3.28.0",
      versionArguments: ["--version"],
      versionPattern: /cmake version (?<version>\d+\.\d+\.\d+)/u,
    },
    remedy: { arch: "sudo pacman -S --needed cmake", ubuntu: "sudo apt-get install -y cmake" },
    required: true,
    tier: "core",
    why: "CMakeLists.txt declares cmake_minimum_required(VERSION 3.28); every preset configures through it.",
  },
  {
    name: "Ninja",
    probe: {
      candidateNames: ["ninja"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed ninja", ubuntu: "sudo apt-get install -y ninja-build" },
    required: true,
    tier: "core",
    why: "Every CMake preset generates Ninja build files; ninja is what actually compiles them.",
  },
  {
    name: "Git",
    probe: {
      candidateNames: ["git"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed git", ubuntu: "sudo apt-get install -y git" },
    required: true,
    tier: "core",
    why: "scripts/vendor-react-native.ts, vendor-skia.ts and vendor-fonts.ts fetch pinned sources through git.",
  },
  {
    name: "Python",
    probe: {
      candidateNames: ["python3", "python"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed python", ubuntu: "sudo apt-get install -y python3" },
    required: true,
    tier: "core",
    why: "packages/core/CMakeLists.txt's Hermes build shells out to Python at configure time.",
  },
  {
    name: "ccache",
    probe: {
      candidateNames: ["ccache"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed ccache", ubuntu: "sudo apt-get install -y ccache" },
    required: false,
    tier: "core",
    why: "packages/core/CMakeLists.txt wires CMAKE_CXX_COMPILER_LAUNCHER to ccache when it is on PATH; the build still works without it, just slower on rebuilds.",
  },
  {
    name: "clang",
    probe: {
      candidateNames: ["clang", "clang-18"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: /clang version (?<version>\d+\.\d+\.\d+)/u,
    },
    remedy: {
      arch: "sudo pacman -S --needed clang llvm",
      ubuntu: "sudo apt-get install -y clang-18 clang-tools-18 libclang-rt-18-dev llvm-18",
    },
    required: false,
    tier: "core",
    why: "CI, Hermes' own Linux CI and Meta's react-native-fantom host all build with clang; gcc is documented but untested.",
  },
  {
    name: "double-conversion",
    probe: {
      fileNamePattern: /^double-conversion\.h$/u,
      kind: "file-glob",
      searchDirectories: ["/usr/include/double-conversion"],
    },
    remedy: {
      arch: "sudo pacman -S --needed double-conversion",
      ubuntu: "sudo apt-get install -y libdouble-conversion-dev",
    },
    required: true,
    tier: "core",
    why: "find_package(double-conversion CONFIG REQUIRED) has no source fallback.",
  },
  {
    name: "fmt",
    probe: { fileNamePattern: /^core\.h$/u, kind: "file-glob", searchDirectories: ["/usr/include/fmt"] },
    remedy: { arch: "sudo pacman -S --needed fmt", ubuntu: "sudo apt-get install -y libfmt-dev" },
    required: true,
    tier: "core",
    why: "find_package(fmt CONFIG REQUIRED) has no source fallback.",
  },
  {
    name: "ICU",
    probe: { fileNamePattern: /^utypes\.h$/u, kind: "file-glob", searchDirectories: ["/usr/include/unicode"] },
    remedy: { arch: "sudo pacman -S --needed icu", ubuntu: "sudo apt-get install -y libicu-dev" },
    required: true,
    tier: "core",
    why: "docs/cpp-toolchain.md documents ICU as having no source fallback, unlike Boost and glog.",
  },
  {
    name: "Boost",
    probe: { fileNamePattern: /^version\.hpp$/u, kind: "file-glob", searchDirectories: ["/usr/include/boost"] },
    remedy: { arch: "sudo pacman -S --needed boost boost-libs", ubuntu: "sudo apt-get install -y libboost-dev" },
    required: false,
    tier: "core",
    why: "find_package(Boost CONFIG QUIET) is tried first; only a machine where it fails falls back to a 145 MB source fetch.",
  },
  {
    name: "glog",
    probe: { fileNamePattern: /^logging\.h$/u, kind: "file-glob", searchDirectories: ["/usr/include/glog"] },
    remedy: { arch: "sudo pacman -S --needed google-glog", ubuntu: "sudo apt-get install -y libgoogle-glog-dev" },
    required: false,
    tier: "core",
    why: "find_package(glog CONFIG QUIET) is tried first; only a machine where it fails falls back to a source build.",
  },
  {
    name: "pkg-config",
    probe: {
      candidateNames: ["pkg-config"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed pkgconf", ubuntu: "sudo apt-get install -y pkg-config" },
    required: true,
    tier: "window",
    why: "packages/core/CMakeLists.txt uses find_package(PkgConfig) to locate freetype2, fontconfig, wayland-client, xkbcommon, wayland-scanner and wayland-protocols.",
  },
  {
    name: "FreeType",
    probe: { kind: "pkg-config", moduleName: "freetype2" },
    remedy: { arch: "sudo pacman -S --needed freetype2", ubuntu: "sudo apt-get install -y libfreetype-dev" },
    required: true,
    tier: "window",
    why: "RNL_ENABLE_SKIA probes pkg-config for freetype2; without it text layout, rnl_window and hello_react --golden are disabled.",
  },
  {
    name: "Fontconfig",
    probe: { kind: "pkg-config", moduleName: "fontconfig" },
    remedy: { arch: "sudo pacman -S --needed fontconfig", ubuntu: "sudo apt-get install -y libfontconfig-dev" },
    required: true,
    tier: "window",
    why: "RNL_ENABLE_SKIA probes pkg-config for fontconfig alongside freetype2.",
  },
  {
    name: "Wayland client",
    probe: { kind: "pkg-config", moduleName: "wayland-client" },
    remedy: { arch: "sudo pacman -S --needed wayland", ubuntu: "sudo apt-get install -y libwayland-dev" },
    required: true,
    tier: "window",
    why: "RNL_ENABLE_WINDOW probes pkg-config for wayland-client to build WaylandWindow and WaylandSeat.",
  },
  {
    name: "Wayland protocols",
    probe: { kind: "pkg-config", moduleName: "wayland-protocols" },
    remedy: { arch: "sudo pacman -S --needed wayland-protocols", ubuntu: "sudo apt-get install -y wayland-protocols" },
    required: true,
    tier: "window",
    why: "packages/core/CMakeLists.txt reads pkg_get_variable(wayland-protocols pkgdatadir) to generate the xdg-shell and zwp_text_input_v3 bindings.",
  },
  {
    name: "wayland-scanner",
    probe: { kind: "pkg-config", moduleName: "wayland-scanner" },
    remedy: { arch: "sudo pacman -S --needed wayland", ubuntu: "sudo apt-get install -y libwayland-dev" },
    required: true,
    tier: "window",
    why: "packages/core/CMakeLists.txt locates it through pkg_get_variable(wayland-scanner wayland_scanner) rather than PATH.",
  },
  {
    name: "xkbcommon",
    probe: { kind: "pkg-config", moduleName: "xkbcommon" },
    remedy: { arch: "sudo pacman -S --needed libxkbcommon", ubuntu: "sudo apt-get install -y libxkbcommon-dev" },
    required: true,
    tier: "window",
    why: "RNL_ENABLE_WINDOW probes pkg-config for xkbcommon; it turns the compositor's keymap into keysyms.",
  },
  {
    name: "Vulkan loader and headers",
    probe: { kind: "pkg-config", moduleName: "vulkan" },
    remedy: {
      arch: "sudo pacman -S --needed vulkan-headers vulkan-icd-loader",
      ubuntu: "sudo apt-get install -y libvulkan-dev",
    },
    required: true,
    tier: "window",
    why: "RNL_ENABLE_WINDOW calls find_package(Vulkan); rnl_window builds a FIFO swapchain on it.",
  },
  {
    name: "Wayland session",
    probe: { kind: "env-var", variableName: "WAYLAND_DISPLAY" },
    remedy: {
      arch: "Run from inside a Wayland session (Hyprland, Sway, ...); this is not a package to install.",
      ubuntu: "Run from inside a Wayland session; this is not a package to install.",
    },
    required: false,
    tier: "window",
    why: "WaylandWindow connects to the compositor named by WAYLAND_DISPLAY; rnl_window has nothing to attach to outside a Wayland session. The window-golden rig sets this itself and does not need a live session.",
  },
  {
    name: "Weston",
    probe: {
      candidateNames: ["weston"],
      kind: "binary",
      versionArguments: ["--version"],
      versionPattern: semanticVersionPattern,
    },
    remedy: { arch: "sudo pacman -S --needed weston", ubuntu: "sudo apt-get install -y weston" },
    required: true,
    tier: "goldens",
    why: "scripts/window-golden.ts drives a headless weston --backend=headless compositor to render the window goldens.",
  },
  {
    name: "Lavapipe (software Vulkan)",
    probe: { kind: "lavapipe-icd" },
    remedy: { arch: "sudo pacman -S --needed vulkan-swrast", ubuntu: "sudo apt-get install -y mesa-vulkan-drivers" },
    required: true,
    tier: "goldens",
    why: "scripts/window-golden.ts needs a lavapipe ICD manifest or libvulkan_lvp.so for VK_ICD_FILENAMES; a machine with only a hardware driver has neither.",
  },
  {
    name: "llvm-cov",
    probe: {
      candidateNames: ["llvm-cov", "llvm-cov-18"],
      kind: "binary",
      overrideEnvironmentVariable: "LLVM_COV",
      versionArguments: ["--version"],
      versionPattern: /LLVM(?: \(.*\))? version (?<version>\d+\.\d+\.\d+)/u,
    },
    remedy: {
      arch: "sudo pacman -S --needed llvm",
      ubuntu: "sudo apt-get install -y llvm-18 (then run with LLVM_COV=llvm-cov-18)",
    },
    required: true,
    tier: "coverage",
    why: "scripts/cpp-coverage.ts runs llvm-cov export --format=lcov to grade the C++ coverage gate.",
  },
  {
    name: "llvm-profdata",
    probe: {
      candidateNames: ["llvm-profdata", "llvm-profdata-18"],
      kind: "binary",
      overrideEnvironmentVariable: "LLVM_PROFDATA",
      versionArguments: ["--version"],
      versionPattern: /LLVM(?: \(.*\))? version (?<version>\d+\.\d+\.\d+)/u,
    },
    remedy: {
      arch: "sudo pacman -S --needed llvm",
      ubuntu: "sudo apt-get install -y llvm-18 (then run with LLVM_PROFDATA=llvm-profdata-18)",
    },
    required: true,
    tier: "coverage",
    why: "scripts/cpp-coverage.ts merges raw profiles with llvm-profdata merge -sparse before exporting lcov.",
  },
];

export { doctorChecks };
